### ISSUE TITLE
Error: Expected Buffer, got undefined

### ISSUE THREAD

**Issue by freedevelopme** [olamigokayphils/blockio-multisig-sweep#4]
Evaluating addresses at i=0
Error: Expected Buffer, got undefined
    at Object.typeforce (/Users/user/blockio-multisig-sweep/node_modules/typeforce/index.js:235:11)
    at ECPair.fromPrivateKey (/Users/user/blockio-multisig-sweep/node_modules/ecpair/src/ecpair.js:23:11)
    at ExtendedKeyService.getKeyAtPath (/Users/user/blockio-multisig-sweep/src/services/ExtendedKeyService.js:27:26)
    at AddressService.generateAddresses (/Users/user/blockio-multisig-sweep/src/services/AddressService.js:15:38)
    at addAddrToMap (/Users/user/blockio-multisig-sweep/src/sweeper.js:275:36)
    at createBalanceMap (/Users/user/blockio-multisig-sweep/src/sweeper.js:261:13)
    at BlockIoSweep.begin (/Users/user/blockio-multisig-sweep/src/sweeper.js:84:27)
    at Sweep (/Users/user/blockio-multisig-sweep/index.js:24:17)
    at Object.<anonymous> (/Users/user/blockio-multisig-sweep/index.js:20:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
Error: Error: Expected Buffer, got undefined
    at BlockIoSweep.begin (/Users/user/blockio-multisig-sweep/src/sweeper.js:198:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Sweep (/Users/user/blockio-multisig-sweep/index.js:24:5)

**Comment by freedevelopme** [comment]
solved
