### ISSUE TITLE
LTC provider

### ISSUE THREAD

**Issue by freedevelopme** [olamigokayphils/blockio-multisig-sweep#5]
Hello. 

Is it possible to add LTC provider? blockcypher.com for example. Current providers doesn't not work with Litecoin.

**Comment by MatthewDEVi** [comment]
Talk to Litecoin Support on the [Litecointalk live support](https://live-litecoin.online/) so that your issue can be looked into.

**Comment by freedevelopme** [comment]
@olamigokayphils kindly check the feasibility

**Comment by olamigokayphils** [comment]
Looking into this now. I'll share some update soonest

**Comment by freedevelopme** [comment]
Hi. Any updates?

**Comment by olamigokayphils** [comment]
@freedevelopme Yes, the BlockCypher API convers extensively for `LTC`. Will push update in few minutes

**Comment by olamigokayphils** [comment]
@freedevelopme Kindly let me know if this address your specific need. Apologies for the late response. Corporate work be saping my time :smiling_face_with_tear: 

If perhaps issues with broadcasting persist: `https://live.blockcypher.com/ltc/pushtx/` can come to immediate rescue

**Comment by freedevelopme** [comment]
Evaluating addresses at i=0
type=P2WSH-P2SH address=MAuBdp1JpchQ6LLMCqVTFPzLS5eaj5KQ6t
Error: Error: Could not get utxo with provider: blockcypher
    at ProviderService.getUtxo (/Users/user/blockio-multisig-sweep/src/services/ProviderService.js:85:11)
    at addAddrToMap (/Users/user/blockio-multisig-sweep/src/sweeper.js:289:44)
    at createBalanceMap (/Users/user/blockio-multisig-sweep/src/sweeper.js:260:13)
    at BlockIoSweep.begin (/Users/user/blockio-multisig-sweep/src/sweeper.js:83:27)
    at Sweep (/Users/user/blockio-multisig-sweep/index.js:24:17)
    at Object.<anonymous> (/Users/user/blockio-multisig-sweep/index.js:20:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
Error: Error: Error: Could not get utxo with provider: blockcypher
    at BlockIoSweep.begin (/Users/vladislavm/blockio-multisig-sweep/src/sweeper.js:197:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Sweep (/Users/user/blockio-multisig-sweep/index.js:24:5)

**Comment by olamigokayphils** [comment]
@freedevelopme Can you confirm or ensure your `constant.js` default are set to:
```
...
BLOCKCHAIN_PROVIDER_DEFAULT: "blockchaincom",
BLOCKCHAIN_PROVIDER_URL_DEFAULT: "https://blockchain.info",
...
```

**Comment by freedevelopme** [comment]
Yes, but blockchain.info is not support LTC. 

Error: Network not supported by provider
    at new ProviderService (/Users/user/blockio-multisig-sweep/src/services/ProviderService.js:12:11)
    at new BlockIoSweep (/Users/user/blockio-multisig-sweep/src/sweeper.js:32:26)
    at Object.<anonymous> (/Users/user/blockio-multisig-sweep/index.js:18:15)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

**Comment by olamigokayphils** [comment]
Got it. We'd have to separate concerns for blockchain.com && blockcypher. I'd made the two depend on each other earlier. I'll work on this shortly.

**Comment by freedevelopme** [comment]
Hi. Any updates?)

**Comment by LinuxCs** [comment]
Yes Please we need ltc ,  block.io suspended my account and i have ltc only inside of it :/

**Comment by freedevelopme** [comment]
@olamigokayphils, Hello. Any updates about ltc provider?

**Comment by olamigokayphils** [comment]
Hiii @freedevelopme @LinuxCs I'm so sorry i've been completely unavailable over the last month. I'll push my local changes soon

**Comment by olamigokayphils** [comment]
@freedevelopme @LinuxCs :+1: https://github.com/olamigokayphils/blockio-multisig-sweep/commit/62560e8148dd816ee97a73684fcf019967226d82. Script now supports LTC

I've duly tested this and used it myself - To move `LTC` from blockio. I'd appreciate another feedback before closing this issue.

**Comment by freedevelopme** [comment]
@olamigokayphils, Hi! It's works, but.. 

 blockcypher API is required token auth for using their API. 
 It's only 20 requests without auth :( 
 
 Is it possible to implement a function that will allow to authenticate using blockcypher token? They have a free plan, you can test it.

**Comment by olamigokayphils** [comment]
@freedevelopme Oops that was an oversight. This feature has been extended. https://github.com/olamigokayphils/blockio-multisig-sweep/commit/7d0beefb7a2ca18c421f7e38db2ca5107c5d271e

**Comment by olamigokayphils** [comment]
@freedevelopme or @LinuxCs Can you confirm the script works well for `ltc`, as required?

**Comment by freedevelopme** [comment]
@olamigokayphils Hello!

Got this error

Evaluating addresses at i=26
type=P2WSH-P2SH address=MQGbGpcExC2R1haWSrJ6U9mUTJY6ZDWqi2
226661660 becomes 22666166000000000
Error: Number exceeds MAX_SAFE_INTEGER
    at getCoinValue (/Users/user/blockio-multisig-sweep/src/sweeper.js:247:11)
    at addAddrToMap (/Users/user/blockio-multisig-sweep/src/sweeper.js:330:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createBalanceMap (/Users/user/blockio-multisig-sweep/src/sweeper.js:264:7)
    at async BlockIoSweep.begin (/Users/user/blockio-multisig-sweep/src/sweeper.js:87:21)
    at async Sweep (/Users/user/blockio-multisig-sweep/index.js:37:5)
Error: Error: Number exceeds MAX_SAFE_INTEGER
    at BlockIoSweep.begin (/Users/user/blockio-multisig-sweep/src/sweeper.js:201:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Sweep (/Users/user/blockio-multisig-sweep/index.js:37:5)
[Error: ENOENT: no such file or directory, open '/Users/user/blockio-multisig-sweep/addresses.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/user/blockio-multisig-sweep/addresses.json'
}

**Comment by olamigokayphils** [comment]
We have two cases here:

1.  `getCoinValue()` raises an alarm "Error: Number exceeds MAX_SAFE_INTEGER"
2. ENOENT: no such file or directory, open '.../user/blockio-multisig-sweep/addresses.json'

For situation 1: The initial developers assumed the balance value will always be returned in BTC & LTC (via `sochain`), however `blockcypher` & `blockchaincom` returns value in SATS & LITS (Satoshi & Litoshis i.e 1/100000000). We had initially bypased the return value but the calculation remained. Thus - I'd add the conditional statement for `sochain` vs other. In your case one of the wrong values  exceed MAX_SATE_INTEGEGER; that's why the issue happend.

For situation 2: `addresses.json` was supposed to be created automatically in your root folder :disappointed: I'll ensure that. You can add it manually [easy solution] but not to worry about that. I'll include that fix in a new update.

N.B: _The purpose of `addresses.json` is to keep track of all addresses and the balance they had before the sweep. I hope other persons would find it useful too._

**Comment by olamigokayphils** [comment]
@freedevelopme  Good news! I'm hoping to hear it :smiley:

**Comment by freedevelopme** [comment]
@olamigokayphils, yes, it's works! Thank you!

**Comment by LinuxCs** [comment]
> @freedevelopme or @LinuxCs Can you confirm the script works well for `ltc`, as required?

thank you so much ,, i really appreciate your constitutes to help us <3

yes now the script is getting the addresses from ltc network and successfully works!

thank you so much <3

**Comment by abetns** [comment]
{ error: 'Limits reached.' }
Sweep Failed:
Error: Error: Error
    at ProviderService.sendTx (/home/kriptonakal/blockio-multisig-sweep/src/services/ProviderService.js:131:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async BlockIoSweep.begin (/home/kriptonakal/blockio-multisig-sweep/src/sweeper.js:212:7)
    at async Sweep (/home/kriptonakal/blockio-multisig-sweep/index.js:37:5)
Error: Error: Error: Error
    at BlockIoSweep.begin (/home/kriptonakal/blockio-multisig-sweep/src/sweeper.js:216:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Sweep (/home/kriptonakal/blockio-multisig-sweep/index.js:37:5)"

please how to fix this

**Comment by olamigokayphils** [comment]
@abetns  Do you mind opening a new issue for this. As this thread has been marked closed and it appears your comment is not directly related.

Be sure to check this previous [resolved issue](https://github.com/olamigokayphils/blockio-multisig-sweep/issues/7) if it addresses your concerns:: 
 
If it doesn't please open a new one and In your issue kindly specify the stage this error happened and which of the supported provider you're using for this as well. I'm happy to assist
