### ISSUE TITLE
{ error: 'Limits reached.' } BTC

### ISSUE THREAD

**Issue by LinuxCs** [olamigokayphils/blockio-multisig-sweep#7]
it works perferct with LTC but when i tried with BTC i got the following error in the final step to broadcast the transaction 

{ error: 'Limits reached.' }
Sweep Failed:
Error: Error: Error
    at ProviderService.sendTx (C:\Users\hp\Desktop\n\blockio-multisig-sweep\src\
services\ProviderService.js:131:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5
)
    at async BlockIoSweep.begin (C:\Users\hp\Desktop\n\blockio-multisig-sweep\sr
c\sweeper.js:212:7)
    at async Sweep (C:\Users\hp\Desktop\n\blockio-multisig-sweep\index.js:37:5)
Error: Error: Error: Error
    at BlockIoSweep.begin (C:\Users\hp\Desktop\n\blockio-multisig-sweep\src\swee
per.js:216:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5
)
    at async Sweep (C:\Users\hp\Desktop\n\blockio-multisig-sweep\index.js:37:5)

**Comment by olamigokayphils** [comment]
You may have exhausted the free/basic limit for `blockcyhper`'s api service. If you already have the Transaction Hex, Kindly leverage BlockCypher web portal. https://live.blockcypher.com/btc/pushtx/

- Copy your Transaction Hex
- Paste In & Broadcast to the Network.

**Comment by LinuxCs** [comment]
i tried to submit the transaction with transaction hex but always receiving this error 

Server Error (500)

changed my network but still facing the same problem

**Comment by LinuxCs** [comment]
successfully broadcast using blockchain   thanks sir <3
